# Generated by Django 3.0.3 on 2020-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('NOT_SENT', 'Не отправлено')], default='NOT_SENT', max_length=8)),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес отправителя')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
        ),
    ]
